### ISSUE TITLE
Support POST versioning

### ISSUE THREAD

**Issue by lakeba** [RIDGIDSoftwareSolutions/versioned-rest-api#8]
Is the ApiRoute expected to work only with GET methods? if I use the same with POST do not work.  

```
  [ApiRoute("ExamplesApi/")]
    [HttpPost]
    public string Post()
    {
        return "Return value for the POST standard method.";
    }

    [ApiRoute("ExamplesApi/", AcceptedVersions = new[] { 2 } )]
    [HttpPost]
    public string NewPostV2()
    {
        return "Return value for the POST version 2 method.";
    }
```

**Comment by jakejgordon** [comment]
It should work for any verb. Is the example not working or do you have an example of something else not working?

**Comment by lakeba** [comment]
your example with one more POST method is not working.

**Comment by jakejgordon** [comment]
I think it is working, but the Example UI didn't have a button to test POST. Below is a screenshot of this working in Postman. I also updated the VersionedRestApi.Examples project so that it starts the testing page by defauilt (instead of making you go to /ExampleMVC explicitly). There is also a button for 'Send a POST request to "/v1/Examples/"' so you can test the POST verb if you'd like. I'll leave the issue open until I hear back from you that it's OK -- or I'll just close it after a few days. Thanks!

![versioned_rest_api_post_example](https://cloud.githubusercontent.com/assets/3045786/11336760/fe0db0e2-91b5-11e5-92ba-7b5353d3e182.jpg)

**Comment by lakeba** [comment]
I found out about the issue, it was my fault actually.

Thank you.

Giuseppe

**Comment by jakejgordon** [comment]
No worries. Closing issue.
